version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - Ocramius
  assignees:
  - Ocramius
  versioning-strategy: increase
  ignore:
  - dependency-name: vimeo/psalm
    versions:
    - 4.5.2
    - 4.6.1
    - 4.6.2
    - 4.6.3
    - 4.6.4
    - 4.7.0
  - dependency-name: laminas/laminas-code
    versions:
    - 4.1.0
