language: php
cache: false

sudo: false

php:
  - 7.4
  - nightly

env:
  matrix:
    - DEPENDENCIES="high"
    - DEPENDENCIES="low"
  global:
    - GIT_NAME:  "'Marco Pivetta'"
    - GIT_EMAIL: ocramius@gmail.com
    - GH_REF:    github.com/Ocramius/ProxyManager
    - secure: HUDB66EnmKFx2A+E3HxvuX/7XSjgfNy8dnzcpG+K9mf/JM5JXZflK3xO3J3LCgSQG6Ptwr2yy//7vX+PdJMdSRTmP+d/dy6v8yLRP+GvYZXLIbuKg7dQjLerOxJcy9JhU2eAEBevc002PwFqLalfhCyWLvLiCof8++E2uGbvTSU=

before_script:
  - sh .travis.install.sh

script:
  - ./vendor/bin/phpunit --disallow-test-output --coverage-clover ./clover.xml --group=Coverage

matrix:
  allow_failures:
    - php: nightly

