name: Tests

on: [push, pull_request]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: ['7.4', '8.0']

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
        env:
          COMPOSER_ROOT_VERSION: dev-master

      -   name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            extensions: "json"
            ini-values: "memory_limit=-1"
            php-version: "${{ matrix.php }}"

      - name: Run Psalm (--shepherd)
        run: ./vendor/bin/psalm --threads=2 --output-format=github --shepherd

      - name: Run PhpCs
        run: ./vendor/bin/phpcs

      - name: Run PhpUnit without coverage
        run: ./vendor/bin/phpunit --disallow-test-output --exclude-group=Coverage

      - name: Run PhpBench
        run: |
          ./vendor/bin/phpbench run --revs=100 --iterations=3 --warmup=1 --report=aggregate

      - name: Run examples
        run: |
          php examples/access-interceptor-scope-localizer.php
          php examples/ghost-object.php
          php examples/ghost-object-skipped-properties.php
          php examples/smart-reference.php
          php examples/virtual-proxy.php
          php tests/static-analysis/access-interceptor-scope-localizer.php
          php tests/static-analysis/lazy-loading-ghost-object.php
          php tests/static-analysis/null-object.php
          php tests/static-analysis/access-interceptor-value-holder.php
          php tests/static-analysis/lazy-loading-value-holder.php
          php tests/static-analysis/remote-object.php
